### ISSUE TITLE
Links and some messages are invinsible

### ISSUE THREAD

**Issue by Saraistupid** [NomadNaomie/BD-Tone-Indicators#6]
Hey! After the latest update (v1.1.1) links and some messages are completely invisible.

Example of an invisible link:
![image](https://user-images.githubusercontent.com/37207067/158654243-2e5bdbff-5947-45b0-8f48-1bf9c6549751.png)

Example of an invisible message:
![image](https://user-images.githubusercontent.com/37207067/158653781-9935b676-9d81-45a0-b8e7-d3ee8be6337d.png)

Plugin off:
![image](https://user-images.githubusercontent.com/37207067/158654557-1b6e837b-c4cd-4b6d-9b4c-52b2e9c2e970.png)
![image](https://user-images.githubusercontent.com/37207067/158654730-82b49a3a-7abd-4faf-8c4b-ee26436d75ec.png)

**Comment by Saraistupid** [comment]
and yes, message with tone indicators do show up 
![image](https://user-images.githubusercontent.com/37207067/158655093-f29961bb-a911-4e65-86c9-f3c0358d3116.png)

**Comment by NomadNaomie** [comment]
Fixed with merging of #5 pending BD's webhook
